CREATE TABLE IF NOT EXISTS User(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(256) NOT NULL,
    HashedPassword VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS Movie(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    User_id INTEGER NOT NULL,
    Title VARCHAR(256) NOT NULL,
    Genre VARCHAR(256) NOT NULL,
    Rating INT NOT NULL
)